// Automatically generated by forge bind-json.

pragma solidity >=0.6.2 <0.9.0;
pragma experimental ABIEncoderV2;

import {GuardedExecutor} from "src/GuardedExecutor.sol";
import {IthacaAccount} from "src/IthacaAccount.sol";
import {MultiSigSigner} from "src/MultiSigSigner.sol";
import {ICommon} from "src/interfaces/ICommon.sol";
import {IEscrow} from "src/interfaces/IEscrow.sol";
import {LibTStack} from "src/libraries/LibTStack.sol";
import {AccountTest} from "test/Account.t.sol";
import {BaseTest} from "test/Base.t.sol";
import {EnforcedOptionParam} from "test/LayerZeroSettler.t.sol";
import {MultiSigSignerTest} from "test/MultiSigSigner.t.sol";
import {OrchestratorTest} from "test/Orchestrator.t.sol";
import {SimulateExecuteTest} from "test/SimulateExecute.t.sol";
import {SignatureWrapper} from "test/utils/interfaces/ICoinbaseSmartWallet.sol";
import {IERC4337EntryPoint, IStakeManager, PackedUserOperation, UserOperation} from "test/utils/interfaces/IERC4337EntryPoint.sol";

interface Vm {
    function parseJsonTypeArray(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata typeDescription) external pure returns (bytes memory);
    function parseJsonType(string calldata json, string calldata key, string calldata typeDescription) external pure returns (bytes memory);
    function serializeJsonType(string calldata typeDescription, bytes memory value) external pure returns (string memory json);
    function serializeJsonType(string calldata objectKey, string calldata valueKey, string calldata typeDescription, bytes memory value) external returns (string memory json);
}
        
library JsonBindings {
    Vm constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    string constant schema_Intent = "Intent(address eoa,bytes executionData,uint256 nonce,address payer,address paymentToken,uint256 paymentMaxAmount,uint256 combinedGas,bytes[] encodedPreCalls,bytes[] encodedFundTransfers,address settler,uint256 expiry,bool isMultichain,address funder,bytes funderSignature,bytes settlerContext,uint256 paymentAmount,address paymentRecipient,bytes signature,bytes paymentSignature,address supportedAccountImplementation)";
    string constant schema_SignedCall = "SignedCall(address eoa,bytes executionData,uint256 nonce,bytes signature)";
    string constant schema_Transfer = "Transfer(address token,uint256 amount)";
    string constant schema_SpendInfo = "SpendInfo(address token,uint8 period,uint256 limit,uint256 spent,uint256 lastUpdated,uint256 currentSpent,uint256 current)";
    string constant schema_CallCheckerInfo = "CallCheckerInfo(address target,address checker)";
    string constant schema_TokenPeriodSpend = "TokenPeriodSpend(uint256 limit,uint256 spent,uint256 lastUpdated)";
    string constant schema__ExecuteTemps = "_ExecuteTemps(DynamicArray approvedERC20s,DynamicArray approvalSpenders,DynamicArray erc20s,DynamicArray transferAmounts,DynamicArray permit2ERC20s,DynamicArray permit2Spenders)DynamicArray(uint256[] data)";
    string constant schema_TStack = "TStack(uint256 slot)";
    string constant schema_Key = "Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)";
    string constant schema_KeyExtraStorage = "KeyExtraStorage(AddressSet checkers)AddressSet(uint256 _spacer)";
    string constant schema_Escrow = "Escrow(bytes12 salt,address depositor,address recipient,address token,uint256 escrowAmount,uint256 refundAmount,uint256 refundTimestamp,address settler,address sender,bytes32 settlementId,uint256 senderChainId)";
    string constant schema_Config = "Config(uint256 threshold,bytes32[] ownerKeyHashes)";
    string constant schema_TargetFunctionPayload = "TargetFunctionPayload(address by,uint256 value,bytes data)";
    string constant schema_PassKey = "PassKey(Key k,uint256 privateKey,bytes32 keyHash)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)";
    string constant schema_MultiSigKey = "MultiSigKey(Key k,uint256 threshold,PassKey[] owners)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)PassKey(Key k,uint256 privateKey,bytes32 keyHash)";
    string constant schema_DelegatedEOA = "DelegatedEOA(address eoa,uint256 privateKey,address d)";
    string constant schema__EstimateGasParams = "_EstimateGasParams(Intent u,uint8 paymentPerGasPrecision,uint256 paymentPerGas,uint256 combinedGasIncrement,uint256 combinedGasVerificationOffset)Intent(address eoa,bytes executionData,uint256 nonce,address payer,address paymentToken,uint256 paymentMaxAmount,uint256 combinedGas,bytes[] encodedPreCalls,bytes[] encodedFundTransfers,address settler,uint256 expiry,bool isMultichain,address funder,bytes funderSignature,bytes settlerContext,uint256 paymentAmount,address paymentRecipient,bytes signature,bytes paymentSignature,address supportedAccountImplementation)";
    string constant schema__TestExecuteWithSignatureTemps = "_TestExecuteWithSignatureTemps(TargetFunctionPayload[] targetFunctionPayloads,Call[] calls,uint256 n,uint256 nonce,bytes opData,bytes executionData)Call(address to,uint256 value,bytes data)TargetFunctionPayload(address by,uint256 value,bytes data)";
    string constant schema__TestUpgradeAccountWithPassKeyTemps = "_TestUpgradeAccountWithPassKeyTemps(uint256 randomVersion,address implementation,Call[] calls,uint256 nonce,bytes opData,bytes executionData)Call(address to,uint256 value,bytes data)";
    string constant schema_DepositInfo = "DepositInfo(uint256 deposit,bool staked,uint112 stake,uint32 unstakeDelaySec,uint48 withdrawTime)";
    string constant schema_StakeInfo = "StakeInfo(uint256 stake,uint256 unstakeDelaySec)";
    string constant schema_PackedUserOperation = "PackedUserOperation(address sender,uint256 nonce,bytes initCode,bytes callData,bytes32 accountGasLimits,uint256 preVerificationGas,bytes32 gasFees,bytes paymasterAndData,bytes signature)";
    string constant schema_UserOperation = "UserOperation(address sender,uint256 nonce,bytes initCode,bytes callData,uint256 callGasLimit,uint256 verificationGasLimit,uint256 preVerificationGas,uint256 maxFeePerGas,uint256 maxPriorityFeePerGas,bytes paymasterAndData,bytes signature)";
    string constant schema_UserOpsPerAggregator = "UserOpsPerAggregator(PackedUserOperation[] userOps,address aggregator,bytes signature)PackedUserOperation(address sender,uint256 nonce,bytes initCode,bytes callData,bytes32 accountGasLimits,uint256 preVerificationGas,bytes32 gasFees,bytes paymasterAndData,bytes signature)";
    string constant schema_ReturnInfo = "ReturnInfo(uint256 preOpGas,uint256 prefund,uint256 accountValidationData,uint256 paymasterValidationData,bytes paymasterContext)";
    string constant schema_SignatureWrapper = "SignatureWrapper(uint8 ownerIndex,bytes signatureData)";
    string constant schema_EnforcedOptionParam = "EnforcedOptionParam(uint32 eid,uint16 msgType,bytes options)";
    string constant schema_MultiSigTestTemps = "MultiSigTestTemps(PassKey[] owners,bytes32[] ownerKeyHashes,uint256 threshold,MultiSigKey multiSigKey,bytes32 digest)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)MultiSigKey(Key k,uint256 threshold,PassKey[] owners)PassKey(Key k,uint256 privateKey,bytes32 keyHash)";
    string constant schema__TestFullFlowTemps = "_TestFullFlowTemps(Intent[] intents,TargetFunctionPayload[] targetFunctionPayloads,DelegatedEOA[] delegatedEOAs,bytes[] encodedIntents)DelegatedEOA(address eoa,uint256 privateKey,address d)Intent(address eoa,bytes executionData,uint256 nonce,address payer,address paymentToken,uint256 paymentMaxAmount,uint256 combinedGas,bytes[] encodedPreCalls,bytes[] encodedFundTransfers,address settler,uint256 expiry,bool isMultichain,address funder,bytes funderSignature,bytes settlerContext,uint256 paymentAmount,address paymentRecipient,bytes signature,bytes paymentSignature,address supportedAccountImplementation)TargetFunctionPayload(address by,uint256 value,bytes data)";
    string constant schema__TestAuthorizeWithPreCallsAndTransferTemps = "_TestAuthorizeWithPreCallsAndTransferTemps(uint256 gExecute,uint256 gCombined,uint256 gUsed,bool success,bytes result,bool testInvalidPreCallEOA,bool testPreCallVerificationError,bool testPreCallError,bool testInit,bool testEOACoalesce,bool testSkipNonce,uint192 superAdminNonceSeqKey,uint192 sessionNonceSeqKey,uint256 retrievedSuperAdminNonce,uint256 retrievedSessionNonce,PassKey kInit,DelegatedEOA d,address eoa)DelegatedEOA(address eoa,uint256 privateKey,address d)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)PassKey(Key k,uint256 privateKey,bytes32 keyHash)";
    string constant schema__TestPayViaAnotherPayerTemps = "_TestPayViaAnotherPayerTemps(address withState,address withSignature,DelegatedEOA withSignatureEOA,address token,uint256 funds,bool isWithState,bool corruptSignature,bool unapprovedOrchestrator,uint256 balanceBefore,DelegatedEOA d)DelegatedEOA(address eoa,uint256 privateKey,address d)";
    string constant schema__TestAccountImplementationVerificationTemps = "_TestAccountImplementationVerificationTemps(bool testImplementationCheck,bool requireWrongImplementation,DelegatedEOA d)DelegatedEOA(address eoa,uint256 privateKey,address d)";
    string constant schema__TestMultiSigTemps = "_TestMultiSigTemps(DelegatedEOA d,address multiSigSigner,uint256 numKeys,MultiSigKey multiSigKey)DelegatedEOA(address eoa,uint256 privateKey,address d)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)MultiSigKey(Key k,uint256 threshold,PassKey[] owners)PassKey(Key k,uint256 privateKey,bytes32 keyHash)";
    string constant schema__TestMultiChainIntentTemps = "_TestMultiChainIntentTemps(address funder,address settler,uint256 funderPrivateKey,address usdcMainnet,address usdcArb,address usdcBase,DelegatedEOA d,PassKey k,Intent baseIntent,Intent arbIntent,Intent outputIntent,bytes32[] leafs,bytes32 root,bytes rootSig,address gasWallet,address relay,address friend,address settlementOracle,address escrowBase,address escrowArb,bytes32 settlementId,bytes32 escrowIdBase,bytes32 escrowIdArb,bytes[] encodedIntents,bytes4[] errs,uint256 snapshot)DelegatedEOA(address eoa,uint256 privateKey,address d)Intent(address eoa,bytes executionData,uint256 nonce,address payer,address paymentToken,uint256 paymentMaxAmount,uint256 combinedGas,bytes[] encodedPreCalls,bytes[] encodedFundTransfers,address settler,uint256 expiry,bool isMultichain,address funder,bytes funderSignature,bytes settlerContext,uint256 paymentAmount,address paymentRecipient,bytes signature,bytes paymentSignature,address supportedAccountImplementation)Key(uint40 expiry,uint8 keyType,bool isSuperAdmin,bytes publicKey)PassKey(Key k,uint256 privateKey,bytes32 keyHash)";
    string constant schema__SimulateExecuteTemps = "_SimulateExecuteTemps(uint256 gasToBurn,uint256 randomness,uint256 gExecute,uint256 gCombined,uint256 gUsed,bytes executionData,bool success,bytes result)";

    function serialize(ICommon.Intent memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Intent, abi.encode(value));
    }

    function serialize(ICommon.Intent memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Intent, abi.encode(value));
    }

    function deserializeIntent(string memory json) public pure returns (ICommon.Intent memory) {
        return abi.decode(vm.parseJsonType(json, schema_Intent), (ICommon.Intent));
    }

    function deserializeIntent(string memory json, string memory path) public pure returns (ICommon.Intent memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Intent), (ICommon.Intent));
    }

    function deserializeIntentArray(string memory json, string memory path) public pure returns (ICommon.Intent[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Intent), (ICommon.Intent[]));
    }

    function serialize(ICommon.SignedCall memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SignedCall, abi.encode(value));
    }

    function serialize(ICommon.SignedCall memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SignedCall, abi.encode(value));
    }

    function deserializeSignedCall(string memory json) public pure returns (ICommon.SignedCall memory) {
        return abi.decode(vm.parseJsonType(json, schema_SignedCall), (ICommon.SignedCall));
    }

    function deserializeSignedCall(string memory json, string memory path) public pure returns (ICommon.SignedCall memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SignedCall), (ICommon.SignedCall));
    }

    function deserializeSignedCallArray(string memory json, string memory path) public pure returns (ICommon.SignedCall[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SignedCall), (ICommon.SignedCall[]));
    }

    function serialize(ICommon.Transfer memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Transfer, abi.encode(value));
    }

    function serialize(ICommon.Transfer memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Transfer, abi.encode(value));
    }

    function deserializeTransfer(string memory json) public pure returns (ICommon.Transfer memory) {
        return abi.decode(vm.parseJsonType(json, schema_Transfer), (ICommon.Transfer));
    }

    function deserializeTransfer(string memory json, string memory path) public pure returns (ICommon.Transfer memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Transfer), (ICommon.Transfer));
    }

    function deserializeTransferArray(string memory json, string memory path) public pure returns (ICommon.Transfer[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Transfer), (ICommon.Transfer[]));
    }

    function serialize(GuardedExecutor.SpendInfo memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SpendInfo, abi.encode(value));
    }

    function serialize(GuardedExecutor.SpendInfo memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SpendInfo, abi.encode(value));
    }

    function deserializeSpendInfo(string memory json) public pure returns (GuardedExecutor.SpendInfo memory) {
        return abi.decode(vm.parseJsonType(json, schema_SpendInfo), (GuardedExecutor.SpendInfo));
    }

    function deserializeSpendInfo(string memory json, string memory path) public pure returns (GuardedExecutor.SpendInfo memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SpendInfo), (GuardedExecutor.SpendInfo));
    }

    function deserializeSpendInfoArray(string memory json, string memory path) public pure returns (GuardedExecutor.SpendInfo[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SpendInfo), (GuardedExecutor.SpendInfo[]));
    }

    function serialize(GuardedExecutor.CallCheckerInfo memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_CallCheckerInfo, abi.encode(value));
    }

    function serialize(GuardedExecutor.CallCheckerInfo memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_CallCheckerInfo, abi.encode(value));
    }

    function deserializeCallCheckerInfo(string memory json) public pure returns (GuardedExecutor.CallCheckerInfo memory) {
        return abi.decode(vm.parseJsonType(json, schema_CallCheckerInfo), (GuardedExecutor.CallCheckerInfo));
    }

    function deserializeCallCheckerInfo(string memory json, string memory path) public pure returns (GuardedExecutor.CallCheckerInfo memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_CallCheckerInfo), (GuardedExecutor.CallCheckerInfo));
    }

    function deserializeCallCheckerInfoArray(string memory json, string memory path) public pure returns (GuardedExecutor.CallCheckerInfo[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_CallCheckerInfo), (GuardedExecutor.CallCheckerInfo[]));
    }

    function serialize(GuardedExecutor.TokenPeriodSpend memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_TokenPeriodSpend, abi.encode(value));
    }

    function serialize(GuardedExecutor.TokenPeriodSpend memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_TokenPeriodSpend, abi.encode(value));
    }

    function deserializeTokenPeriodSpend(string memory json) public pure returns (GuardedExecutor.TokenPeriodSpend memory) {
        return abi.decode(vm.parseJsonType(json, schema_TokenPeriodSpend), (GuardedExecutor.TokenPeriodSpend));
    }

    function deserializeTokenPeriodSpend(string memory json, string memory path) public pure returns (GuardedExecutor.TokenPeriodSpend memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_TokenPeriodSpend), (GuardedExecutor.TokenPeriodSpend));
    }

    function deserializeTokenPeriodSpendArray(string memory json, string memory path) public pure returns (GuardedExecutor.TokenPeriodSpend[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_TokenPeriodSpend), (GuardedExecutor.TokenPeriodSpend[]));
    }

    function serialize(GuardedExecutor._ExecuteTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__ExecuteTemps, abi.encode(value));
    }

    function serialize(GuardedExecutor._ExecuteTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__ExecuteTemps, abi.encode(value));
    }

    function deserialize_ExecuteTemps(string memory json) public pure returns (GuardedExecutor._ExecuteTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__ExecuteTemps), (GuardedExecutor._ExecuteTemps));
    }

    function deserialize_ExecuteTemps(string memory json, string memory path) public pure returns (GuardedExecutor._ExecuteTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__ExecuteTemps), (GuardedExecutor._ExecuteTemps));
    }

    function deserialize_ExecuteTempsArray(string memory json, string memory path) public pure returns (GuardedExecutor._ExecuteTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__ExecuteTemps), (GuardedExecutor._ExecuteTemps[]));
    }

    function serialize(LibTStack.TStack memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_TStack, abi.encode(value));
    }

    function serialize(LibTStack.TStack memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_TStack, abi.encode(value));
    }

    function deserializeTStack(string memory json) public pure returns (LibTStack.TStack memory) {
        return abi.decode(vm.parseJsonType(json, schema_TStack), (LibTStack.TStack));
    }

    function deserializeTStack(string memory json, string memory path) public pure returns (LibTStack.TStack memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_TStack), (LibTStack.TStack));
    }

    function deserializeTStackArray(string memory json, string memory path) public pure returns (LibTStack.TStack[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_TStack), (LibTStack.TStack[]));
    }

    function serialize(IthacaAccount.Key memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Key, abi.encode(value));
    }

    function serialize(IthacaAccount.Key memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Key, abi.encode(value));
    }

    function deserializeKey(string memory json) public pure returns (IthacaAccount.Key memory) {
        return abi.decode(vm.parseJsonType(json, schema_Key), (IthacaAccount.Key));
    }

    function deserializeKey(string memory json, string memory path) public pure returns (IthacaAccount.Key memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Key), (IthacaAccount.Key));
    }

    function deserializeKeyArray(string memory json, string memory path) public pure returns (IthacaAccount.Key[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Key), (IthacaAccount.Key[]));
    }

    function serialize(IthacaAccount.KeyExtraStorage memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_KeyExtraStorage, abi.encode(value));
    }

    function serialize(IthacaAccount.KeyExtraStorage memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_KeyExtraStorage, abi.encode(value));
    }

    function deserializeKeyExtraStorage(string memory json) public pure returns (IthacaAccount.KeyExtraStorage memory) {
        return abi.decode(vm.parseJsonType(json, schema_KeyExtraStorage), (IthacaAccount.KeyExtraStorage));
    }

    function deserializeKeyExtraStorage(string memory json, string memory path) public pure returns (IthacaAccount.KeyExtraStorage memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_KeyExtraStorage), (IthacaAccount.KeyExtraStorage));
    }

    function deserializeKeyExtraStorageArray(string memory json, string memory path) public pure returns (IthacaAccount.KeyExtraStorage[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_KeyExtraStorage), (IthacaAccount.KeyExtraStorage[]));
    }

    function serialize(IEscrow.Escrow memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Escrow, abi.encode(value));
    }

    function serialize(IEscrow.Escrow memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Escrow, abi.encode(value));
    }

    function deserializeEscrow(string memory json) public pure returns (IEscrow.Escrow memory) {
        return abi.decode(vm.parseJsonType(json, schema_Escrow), (IEscrow.Escrow));
    }

    function deserializeEscrow(string memory json, string memory path) public pure returns (IEscrow.Escrow memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Escrow), (IEscrow.Escrow));
    }

    function deserializeEscrowArray(string memory json, string memory path) public pure returns (IEscrow.Escrow[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Escrow), (IEscrow.Escrow[]));
    }

    function serialize(MultiSigSigner.Config memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_Config, abi.encode(value));
    }

    function serialize(MultiSigSigner.Config memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_Config, abi.encode(value));
    }

    function deserializeConfig(string memory json) public pure returns (MultiSigSigner.Config memory) {
        return abi.decode(vm.parseJsonType(json, schema_Config), (MultiSigSigner.Config));
    }

    function deserializeConfig(string memory json, string memory path) public pure returns (MultiSigSigner.Config memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_Config), (MultiSigSigner.Config));
    }

    function deserializeConfigArray(string memory json, string memory path) public pure returns (MultiSigSigner.Config[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_Config), (MultiSigSigner.Config[]));
    }

    function serialize(BaseTest.TargetFunctionPayload memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_TargetFunctionPayload, abi.encode(value));
    }

    function serialize(BaseTest.TargetFunctionPayload memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_TargetFunctionPayload, abi.encode(value));
    }

    function deserializeTargetFunctionPayload(string memory json) public pure returns (BaseTest.TargetFunctionPayload memory) {
        return abi.decode(vm.parseJsonType(json, schema_TargetFunctionPayload), (BaseTest.TargetFunctionPayload));
    }

    function deserializeTargetFunctionPayload(string memory json, string memory path) public pure returns (BaseTest.TargetFunctionPayload memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_TargetFunctionPayload), (BaseTest.TargetFunctionPayload));
    }

    function deserializeTargetFunctionPayloadArray(string memory json, string memory path) public pure returns (BaseTest.TargetFunctionPayload[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_TargetFunctionPayload), (BaseTest.TargetFunctionPayload[]));
    }

    function serialize(BaseTest.PassKey memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_PassKey, abi.encode(value));
    }

    function serialize(BaseTest.PassKey memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_PassKey, abi.encode(value));
    }

    function deserializePassKey(string memory json) public pure returns (BaseTest.PassKey memory) {
        return abi.decode(vm.parseJsonType(json, schema_PassKey), (BaseTest.PassKey));
    }

    function deserializePassKey(string memory json, string memory path) public pure returns (BaseTest.PassKey memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_PassKey), (BaseTest.PassKey));
    }

    function deserializePassKeyArray(string memory json, string memory path) public pure returns (BaseTest.PassKey[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_PassKey), (BaseTest.PassKey[]));
    }

    function serialize(BaseTest.MultiSigKey memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_MultiSigKey, abi.encode(value));
    }

    function serialize(BaseTest.MultiSigKey memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_MultiSigKey, abi.encode(value));
    }

    function deserializeMultiSigKey(string memory json) public pure returns (BaseTest.MultiSigKey memory) {
        return abi.decode(vm.parseJsonType(json, schema_MultiSigKey), (BaseTest.MultiSigKey));
    }

    function deserializeMultiSigKey(string memory json, string memory path) public pure returns (BaseTest.MultiSigKey memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_MultiSigKey), (BaseTest.MultiSigKey));
    }

    function deserializeMultiSigKeyArray(string memory json, string memory path) public pure returns (BaseTest.MultiSigKey[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_MultiSigKey), (BaseTest.MultiSigKey[]));
    }

    function serialize(BaseTest.DelegatedEOA memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_DelegatedEOA, abi.encode(value));
    }

    function serialize(BaseTest.DelegatedEOA memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_DelegatedEOA, abi.encode(value));
    }

    function deserializeDelegatedEOA(string memory json) public pure returns (BaseTest.DelegatedEOA memory) {
        return abi.decode(vm.parseJsonType(json, schema_DelegatedEOA), (BaseTest.DelegatedEOA));
    }

    function deserializeDelegatedEOA(string memory json, string memory path) public pure returns (BaseTest.DelegatedEOA memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_DelegatedEOA), (BaseTest.DelegatedEOA));
    }

    function deserializeDelegatedEOAArray(string memory json, string memory path) public pure returns (BaseTest.DelegatedEOA[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_DelegatedEOA), (BaseTest.DelegatedEOA[]));
    }

    function serialize(BaseTest._EstimateGasParams memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__EstimateGasParams, abi.encode(value));
    }

    function serialize(BaseTest._EstimateGasParams memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__EstimateGasParams, abi.encode(value));
    }

    function deserialize_EstimateGasParams(string memory json) public pure returns (BaseTest._EstimateGasParams memory) {
        return abi.decode(vm.parseJsonType(json, schema__EstimateGasParams), (BaseTest._EstimateGasParams));
    }

    function deserialize_EstimateGasParams(string memory json, string memory path) public pure returns (BaseTest._EstimateGasParams memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__EstimateGasParams), (BaseTest._EstimateGasParams));
    }

    function deserialize_EstimateGasParamsArray(string memory json, string memory path) public pure returns (BaseTest._EstimateGasParams[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__EstimateGasParams), (BaseTest._EstimateGasParams[]));
    }

    function serialize(AccountTest._TestExecuteWithSignatureTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestExecuteWithSignatureTemps, abi.encode(value));
    }

    function serialize(AccountTest._TestExecuteWithSignatureTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestExecuteWithSignatureTemps, abi.encode(value));
    }

    function deserialize_TestExecuteWithSignatureTemps(string memory json) public pure returns (AccountTest._TestExecuteWithSignatureTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestExecuteWithSignatureTemps), (AccountTest._TestExecuteWithSignatureTemps));
    }

    function deserialize_TestExecuteWithSignatureTemps(string memory json, string memory path) public pure returns (AccountTest._TestExecuteWithSignatureTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestExecuteWithSignatureTemps), (AccountTest._TestExecuteWithSignatureTemps));
    }

    function deserialize_TestExecuteWithSignatureTempsArray(string memory json, string memory path) public pure returns (AccountTest._TestExecuteWithSignatureTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestExecuteWithSignatureTemps), (AccountTest._TestExecuteWithSignatureTemps[]));
    }

    function serialize(AccountTest._TestUpgradeAccountWithPassKeyTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestUpgradeAccountWithPassKeyTemps, abi.encode(value));
    }

    function serialize(AccountTest._TestUpgradeAccountWithPassKeyTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestUpgradeAccountWithPassKeyTemps, abi.encode(value));
    }

    function deserialize_TestUpgradeAccountWithPassKeyTemps(string memory json) public pure returns (AccountTest._TestUpgradeAccountWithPassKeyTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestUpgradeAccountWithPassKeyTemps), (AccountTest._TestUpgradeAccountWithPassKeyTemps));
    }

    function deserialize_TestUpgradeAccountWithPassKeyTemps(string memory json, string memory path) public pure returns (AccountTest._TestUpgradeAccountWithPassKeyTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestUpgradeAccountWithPassKeyTemps), (AccountTest._TestUpgradeAccountWithPassKeyTemps));
    }

    function deserialize_TestUpgradeAccountWithPassKeyTempsArray(string memory json, string memory path) public pure returns (AccountTest._TestUpgradeAccountWithPassKeyTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestUpgradeAccountWithPassKeyTemps), (AccountTest._TestUpgradeAccountWithPassKeyTemps[]));
    }

    function serialize(IStakeManager.DepositInfo memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_DepositInfo, abi.encode(value));
    }

    function serialize(IStakeManager.DepositInfo memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_DepositInfo, abi.encode(value));
    }

    function deserializeDepositInfo(string memory json) public pure returns (IStakeManager.DepositInfo memory) {
        return abi.decode(vm.parseJsonType(json, schema_DepositInfo), (IStakeManager.DepositInfo));
    }

    function deserializeDepositInfo(string memory json, string memory path) public pure returns (IStakeManager.DepositInfo memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_DepositInfo), (IStakeManager.DepositInfo));
    }

    function deserializeDepositInfoArray(string memory json, string memory path) public pure returns (IStakeManager.DepositInfo[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_DepositInfo), (IStakeManager.DepositInfo[]));
    }

    function serialize(IStakeManager.StakeInfo memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_StakeInfo, abi.encode(value));
    }

    function serialize(IStakeManager.StakeInfo memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_StakeInfo, abi.encode(value));
    }

    function deserializeStakeInfo(string memory json) public pure returns (IStakeManager.StakeInfo memory) {
        return abi.decode(vm.parseJsonType(json, schema_StakeInfo), (IStakeManager.StakeInfo));
    }

    function deserializeStakeInfo(string memory json, string memory path) public pure returns (IStakeManager.StakeInfo memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_StakeInfo), (IStakeManager.StakeInfo));
    }

    function deserializeStakeInfoArray(string memory json, string memory path) public pure returns (IStakeManager.StakeInfo[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_StakeInfo), (IStakeManager.StakeInfo[]));
    }

    function serialize(PackedUserOperation memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_PackedUserOperation, abi.encode(value));
    }

    function serialize(PackedUserOperation memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_PackedUserOperation, abi.encode(value));
    }

    function deserializePackedUserOperation(string memory json) public pure returns (PackedUserOperation memory) {
        return abi.decode(vm.parseJsonType(json, schema_PackedUserOperation), (PackedUserOperation));
    }

    function deserializePackedUserOperation(string memory json, string memory path) public pure returns (PackedUserOperation memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_PackedUserOperation), (PackedUserOperation));
    }

    function deserializePackedUserOperationArray(string memory json, string memory path) public pure returns (PackedUserOperation[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_PackedUserOperation), (PackedUserOperation[]));
    }

    function serialize(UserOperation memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_UserOperation, abi.encode(value));
    }

    function serialize(UserOperation memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_UserOperation, abi.encode(value));
    }

    function deserializeUserOperation(string memory json) public pure returns (UserOperation memory) {
        return abi.decode(vm.parseJsonType(json, schema_UserOperation), (UserOperation));
    }

    function deserializeUserOperation(string memory json, string memory path) public pure returns (UserOperation memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_UserOperation), (UserOperation));
    }

    function deserializeUserOperationArray(string memory json, string memory path) public pure returns (UserOperation[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_UserOperation), (UserOperation[]));
    }

    function serialize(IERC4337EntryPoint.UserOpsPerAggregator memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_UserOpsPerAggregator, abi.encode(value));
    }

    function serialize(IERC4337EntryPoint.UserOpsPerAggregator memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_UserOpsPerAggregator, abi.encode(value));
    }

    function deserializeUserOpsPerAggregator(string memory json) public pure returns (IERC4337EntryPoint.UserOpsPerAggregator memory) {
        return abi.decode(vm.parseJsonType(json, schema_UserOpsPerAggregator), (IERC4337EntryPoint.UserOpsPerAggregator));
    }

    function deserializeUserOpsPerAggregator(string memory json, string memory path) public pure returns (IERC4337EntryPoint.UserOpsPerAggregator memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_UserOpsPerAggregator), (IERC4337EntryPoint.UserOpsPerAggregator));
    }

    function deserializeUserOpsPerAggregatorArray(string memory json, string memory path) public pure returns (IERC4337EntryPoint.UserOpsPerAggregator[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_UserOpsPerAggregator), (IERC4337EntryPoint.UserOpsPerAggregator[]));
    }

    function serialize(IERC4337EntryPoint.ReturnInfo memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_ReturnInfo, abi.encode(value));
    }

    function serialize(IERC4337EntryPoint.ReturnInfo memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_ReturnInfo, abi.encode(value));
    }

    function deserializeReturnInfo(string memory json) public pure returns (IERC4337EntryPoint.ReturnInfo memory) {
        return abi.decode(vm.parseJsonType(json, schema_ReturnInfo), (IERC4337EntryPoint.ReturnInfo));
    }

    function deserializeReturnInfo(string memory json, string memory path) public pure returns (IERC4337EntryPoint.ReturnInfo memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_ReturnInfo), (IERC4337EntryPoint.ReturnInfo));
    }

    function deserializeReturnInfoArray(string memory json, string memory path) public pure returns (IERC4337EntryPoint.ReturnInfo[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_ReturnInfo), (IERC4337EntryPoint.ReturnInfo[]));
    }

    function serialize(SignatureWrapper memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_SignatureWrapper, abi.encode(value));
    }

    function serialize(SignatureWrapper memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_SignatureWrapper, abi.encode(value));
    }

    function deserializeSignatureWrapper(string memory json) public pure returns (SignatureWrapper memory) {
        return abi.decode(vm.parseJsonType(json, schema_SignatureWrapper), (SignatureWrapper));
    }

    function deserializeSignatureWrapper(string memory json, string memory path) public pure returns (SignatureWrapper memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_SignatureWrapper), (SignatureWrapper));
    }

    function deserializeSignatureWrapperArray(string memory json, string memory path) public pure returns (SignatureWrapper[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_SignatureWrapper), (SignatureWrapper[]));
    }

    function serialize(EnforcedOptionParam memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_EnforcedOptionParam, abi.encode(value));
    }

    function serialize(EnforcedOptionParam memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_EnforcedOptionParam, abi.encode(value));
    }

    function deserializeEnforcedOptionParam(string memory json) public pure returns (EnforcedOptionParam memory) {
        return abi.decode(vm.parseJsonType(json, schema_EnforcedOptionParam), (EnforcedOptionParam));
    }

    function deserializeEnforcedOptionParam(string memory json, string memory path) public pure returns (EnforcedOptionParam memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_EnforcedOptionParam), (EnforcedOptionParam));
    }

    function deserializeEnforcedOptionParamArray(string memory json, string memory path) public pure returns (EnforcedOptionParam[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_EnforcedOptionParam), (EnforcedOptionParam[]));
    }

    function serialize(MultiSigSignerTest.MultiSigTestTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema_MultiSigTestTemps, abi.encode(value));
    }

    function serialize(MultiSigSignerTest.MultiSigTestTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema_MultiSigTestTemps, abi.encode(value));
    }

    function deserializeMultiSigTestTemps(string memory json) public pure returns (MultiSigSignerTest.MultiSigTestTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema_MultiSigTestTemps), (MultiSigSignerTest.MultiSigTestTemps));
    }

    function deserializeMultiSigTestTemps(string memory json, string memory path) public pure returns (MultiSigSignerTest.MultiSigTestTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema_MultiSigTestTemps), (MultiSigSignerTest.MultiSigTestTemps));
    }

    function deserializeMultiSigTestTempsArray(string memory json, string memory path) public pure returns (MultiSigSignerTest.MultiSigTestTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema_MultiSigTestTemps), (MultiSigSignerTest.MultiSigTestTemps[]));
    }

    function serialize(OrchestratorTest._TestFullFlowTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestFullFlowTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestFullFlowTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestFullFlowTemps, abi.encode(value));
    }

    function deserialize_TestFullFlowTemps(string memory json) public pure returns (OrchestratorTest._TestFullFlowTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestFullFlowTemps), (OrchestratorTest._TestFullFlowTemps));
    }

    function deserialize_TestFullFlowTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestFullFlowTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestFullFlowTemps), (OrchestratorTest._TestFullFlowTemps));
    }

    function deserialize_TestFullFlowTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestFullFlowTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestFullFlowTemps), (OrchestratorTest._TestFullFlowTemps[]));
    }

    function serialize(OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestAuthorizeWithPreCallsAndTransferTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestAuthorizeWithPreCallsAndTransferTemps, abi.encode(value));
    }

    function deserialize_TestAuthorizeWithPreCallsAndTransferTemps(string memory json) public pure returns (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestAuthorizeWithPreCallsAndTransferTemps), (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps));
    }

    function deserialize_TestAuthorizeWithPreCallsAndTransferTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestAuthorizeWithPreCallsAndTransferTemps), (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps));
    }

    function deserialize_TestAuthorizeWithPreCallsAndTransferTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestAuthorizeWithPreCallsAndTransferTemps), (OrchestratorTest._TestAuthorizeWithPreCallsAndTransferTemps[]));
    }

    function serialize(OrchestratorTest._TestPayViaAnotherPayerTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestPayViaAnotherPayerTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestPayViaAnotherPayerTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestPayViaAnotherPayerTemps, abi.encode(value));
    }

    function deserialize_TestPayViaAnotherPayerTemps(string memory json) public pure returns (OrchestratorTest._TestPayViaAnotherPayerTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestPayViaAnotherPayerTemps), (OrchestratorTest._TestPayViaAnotherPayerTemps));
    }

    function deserialize_TestPayViaAnotherPayerTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestPayViaAnotherPayerTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestPayViaAnotherPayerTemps), (OrchestratorTest._TestPayViaAnotherPayerTemps));
    }

    function deserialize_TestPayViaAnotherPayerTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestPayViaAnotherPayerTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestPayViaAnotherPayerTemps), (OrchestratorTest._TestPayViaAnotherPayerTemps[]));
    }

    function serialize(OrchestratorTest._TestAccountImplementationVerificationTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestAccountImplementationVerificationTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestAccountImplementationVerificationTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestAccountImplementationVerificationTemps, abi.encode(value));
    }

    function deserialize_TestAccountImplementationVerificationTemps(string memory json) public pure returns (OrchestratorTest._TestAccountImplementationVerificationTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestAccountImplementationVerificationTemps), (OrchestratorTest._TestAccountImplementationVerificationTemps));
    }

    function deserialize_TestAccountImplementationVerificationTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestAccountImplementationVerificationTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestAccountImplementationVerificationTemps), (OrchestratorTest._TestAccountImplementationVerificationTemps));
    }

    function deserialize_TestAccountImplementationVerificationTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestAccountImplementationVerificationTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestAccountImplementationVerificationTemps), (OrchestratorTest._TestAccountImplementationVerificationTemps[]));
    }

    function serialize(OrchestratorTest._TestMultiSigTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestMultiSigTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestMultiSigTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestMultiSigTemps, abi.encode(value));
    }

    function deserialize_TestMultiSigTemps(string memory json) public pure returns (OrchestratorTest._TestMultiSigTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestMultiSigTemps), (OrchestratorTest._TestMultiSigTemps));
    }

    function deserialize_TestMultiSigTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestMultiSigTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestMultiSigTemps), (OrchestratorTest._TestMultiSigTemps));
    }

    function deserialize_TestMultiSigTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestMultiSigTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestMultiSigTemps), (OrchestratorTest._TestMultiSigTemps[]));
    }

    function serialize(OrchestratorTest._TestMultiChainIntentTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__TestMultiChainIntentTemps, abi.encode(value));
    }

    function serialize(OrchestratorTest._TestMultiChainIntentTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__TestMultiChainIntentTemps, abi.encode(value));
    }

    function deserialize_TestMultiChainIntentTemps(string memory json) public pure returns (OrchestratorTest._TestMultiChainIntentTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__TestMultiChainIntentTemps), (OrchestratorTest._TestMultiChainIntentTemps));
    }

    function deserialize_TestMultiChainIntentTemps(string memory json, string memory path) public pure returns (OrchestratorTest._TestMultiChainIntentTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__TestMultiChainIntentTemps), (OrchestratorTest._TestMultiChainIntentTemps));
    }

    function deserialize_TestMultiChainIntentTempsArray(string memory json, string memory path) public pure returns (OrchestratorTest._TestMultiChainIntentTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__TestMultiChainIntentTemps), (OrchestratorTest._TestMultiChainIntentTemps[]));
    }

    function serialize(SimulateExecuteTest._SimulateExecuteTemps memory value) internal pure returns (string memory) {
        return vm.serializeJsonType(schema__SimulateExecuteTemps, abi.encode(value));
    }

    function serialize(SimulateExecuteTest._SimulateExecuteTemps memory value, string memory objectKey, string memory valueKey) internal returns (string memory) {
        return vm.serializeJsonType(objectKey, valueKey, schema__SimulateExecuteTemps, abi.encode(value));
    }

    function deserialize_SimulateExecuteTemps(string memory json) public pure returns (SimulateExecuteTest._SimulateExecuteTemps memory) {
        return abi.decode(vm.parseJsonType(json, schema__SimulateExecuteTemps), (SimulateExecuteTest._SimulateExecuteTemps));
    }

    function deserialize_SimulateExecuteTemps(string memory json, string memory path) public pure returns (SimulateExecuteTest._SimulateExecuteTemps memory) {
        return abi.decode(vm.parseJsonType(json, path, schema__SimulateExecuteTemps), (SimulateExecuteTest._SimulateExecuteTemps));
    }

    function deserialize_SimulateExecuteTempsArray(string memory json, string memory path) public pure returns (SimulateExecuteTest._SimulateExecuteTemps[] memory) {
        return abi.decode(vm.parseJsonTypeArray(json, path, schema__SimulateExecuteTemps), (SimulateExecuteTest._SimulateExecuteTemps[]));
    }
}
