name: Test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly 

      - name: Build
        run: |
          forge build

      - name: Check formatting
        run: |
          forge fmt --check

      - name: Run tests
        env:
          UPGRADE_TEST_RPC_URL: ${{ secrets.UPGRADE_TEST_RPC_URL }}
          UPGRADE_TEST_OLD_PROXY: ${{ secrets.UPGRADE_TEST_OLD_PROXY }}
          UPGRADE_TEST_OLD_VERSION: ${{ secrets.UPGRADE_TEST_OLD_VERSION }}
        run: |
          forge test -vvv

      - name: Update snapshots
        run: |
          forge snapshot --isolate --match-contract Benchmark --via-ir
          if [ -n "$(git status --porcelain snapshots/)" ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add snapshots/
            git commit -m "chore: update gas snapshots"
            git push
          fi
