name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # TODO: use stable once https://github.com/foundry-rs/foundry/pull/9979 is released.
          version: nightly
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.deployer }}
        # TODO: remove the --evm-version argument once https://github.com/blockscout/blockscout/pull/12115 is released.
        run: |
          forge script DeployAllScript \
            --rpc-url "https://odyssey.ithaca.xyz" \
            --broadcast -q --verify --verifier blockscout \
            --verifier-url "https://odyssey-explorer.ithaca.xyz/api" \
            --evm-version cancun

          # Print addresses.
          jq -r '.transactions[].additionalContracts | 
            "EntryPoint: " + .[0].address, 
            "Delegation: "  + .[1].address, 
            "EIP7702Proxy: " + .[2].address' \
            broadcast/DeployAll.s.sol/911867/run-latest.json

          # Build the EIP7702Proxy with exact bytecode for verification.
          cp lib/solady/src/accounts/EIP7702Proxy.sol src/EIP7702Proxy.sol
          forge clean
          forge build --use=0.8.28 --optimizer-runs=200 --evm-version=cancun

          # Prepare constructor args for EIP7702Proxy verification.
          DELEGATION_ADDRESS=$(jq -r '.transactions[].additionalContracts[1].address' broadcast/DeployAll.s.sol/911867/run-latest.json | sed 's/^0x//')
          CONSTRUCTOR_ARGS="0x000000000000000000000000${DELEGATION_ADDRESS}0000000000000000000000000000000000000000000000000000000000000000"

          # Verify the EIP7702Proxy.
          EIP7702PROXY_ADDRESS=$(jq -r '.transactions[].additionalContracts[2].address' broadcast/DeployAll.s.sol/911867/run-latest.json)

          forge verify-contract "$EIP7702PROXY_ADDRESS" \
            "src/EIP7702Proxy.sol:EIP7702Proxy" \
            --compiler-version=0.8.28 \
            --optimizer-runs=200 \
            --evm-version=cancun \
            --constructor-args "$CONSTRUCTOR_ARGS" \
            --chain odyssey \
            --skip-is-verified-check \
            --verifier blockscout \
            --verifier-url "https://odyssey-explorer.ithaca.xyz/api"

          # EIP7702Proxy verification cleanup.
          rm src/EIP7702Proxy.sol
