name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          # TODO: use stable once https://github.com/foundry-rs/foundry/pull/9979 is released.
          version: nightly
      - name: Deploy
        env:
          PRIVATE_KEY: ${{ secrets.deployer }}
          FUNDER: ${{ secrets.deployer }}
          FUNDER_OWNER: ${{ secrets.deployer }}
          SETTLER_OWNER: ${{ secrets.deployer }}
        # TODO: remove the --evm-version argument once https://github.com/blockscout/blockscout/pull/12115 is released.
        # TODO: re-add --verify --verifier blockscout --verifier-url "https://odyssey-explorer.ithaca.xyz/api"
        run: |
          # For testnets and devnets, pause authority is the same as the deployer.
          export PAUSE_AUTHORITY=$(cast wallet addr "$PRIVATE_KEY")
          export FUNDER=$(cast wallet addr "$FUNDER")
          export FUNDER_OWNER=$(cast wallet addr "$FUNDER_OWNER")
          export SETTLER_OWNER=$(cast wallet addr "$SETTLER_OWNER")

          forge script DeployAllScript \
            --rpc-url "https://porto-dev.rpc.ithaca.xyz/" \
            --broadcast -q \
            --private-key $PRIVATE_KEY \
            --evm-version cancun && \
          jq -r '.transactions | "Orchestrator: " + .[0].contractAddress, "IthacaAccount: " + .[1].contractAddress, "EIP7702Proxy: " + .[2].contractAddress, "Simulator: " + .[3].contractAddress, "Funder: " + .[4].contractAddress, "SimpleSettler: " + .[5].contractAddress, "Escrow: " + .[6].contractAddress' broadcast/DeployAll.s.sol/28404/run-latest.json
