name: Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check-bytecode-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build contracts on base branch
        run: |
          git checkout origin/${{ github.base_ref }}
          forge clean
          forge install
          forge build --force
          mkdir -p /tmp/base-artifacts
          cp -r out/* /tmp/base-artifacts/
      
      - name: Build contracts on PR branch
        run: |
          git checkout ${{ github.head_ref }}
          forge clean
          forge install
          forge build --force
      
      - name: Check bytecode changes and version
        id: check
        run: |
          node prep/check-bytecode-changes.js /tmp/base-artifacts out
      
      - name: Bump version if needed
        if: steps.check.outputs.needs_version_bump == 'true'
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Bump patch version
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          PATCH=$((version_parts[2] + 1))
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$PATCH"
          
          echo "Bumping version from $CURRENT_VERSION to $NEW_VERSION"
          
          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version
          
          # Update Solidity files using the upgrade script
          node prep/update-version.js
          
          # Commit changes
          git add .
          git commit -m "chore: bump version to $NEW_VERSION due to bytecode changes"
          
          # Push to the PR branch
          git push origin HEAD:${{ github.head_ref }}
      
      - name: Create PR comment
        if: steps.check.outputs.needs_version_bump == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Bytecode changes detected! Version has been automatically bumped and EIP-712 domain versions have been updated.'
            })