name: Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check-bytecode-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build contracts on base branch
        run: |
          git checkout origin/${{ github.base_ref }}
          forge clean
          forge install
          forge build --force
          mkdir -p /tmp/base-artifacts
          cp -r out/* /tmp/base-artifacts/
      
      - name: Build contracts on PR branch
        run: |
          git checkout -f ${{ github.event.pull_request.head.sha }}
          forge clean
          forge install
          forge build --force
      
      - name: Check bytecode changes and version
        id: check
        run: |
          node prep/check-bytecode-changes.js /tmp/base-artifacts out
      
      - name: Bump version if needed
        if: steps.check.outputs.needs_version_bump == 'true'
        run: |
          # Get the contracts that need bumping
          CONTRACTS_TO_BUMP="${{ steps.check.outputs.contracts_to_bump }}"

          echo "Bumping versions for contracts: $CONTRACTS_TO_BUMP"

          # Update Solidity files using the upgrade script with specific contracts
          CONTRACTS_TO_BUMP="$CONTRACTS_TO_BUMP" node prep/update-version.js

      - name: Commit version bump changes
        if: steps.check.outputs.needs_version_bump == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump contract versions due to bytecode changes - Contracts updated: ${{ steps.check.outputs.contracts_to_bump }}"
          file_pattern: "src/*.sol"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
      
      - name: Create PR comment
        if: steps.check.outputs.needs_version_bump == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const contractsToBump = '${{ steps.check.outputs.contracts_to_bump }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 Bytecode changes detected! EIP-712 domain versions have been automatically updated for: ${contractsToBump}`
            })